### ISSUE TITLE
command 'htmlToCssConfig' not found

### ISSUE THREAD

**Issue by PixelT** [solnurkarim/HTML-to-CSS-autocompletion#1]
I installed this extension, but it doesn't work - when I try to run command `HTML to CSS autocompletion: Extension Configuration` I get an error: 
`command 'htmlToCssConfig' not found`

**Comment by solnurkarim** [comment]
Seems like an issue on VSCode side. If it still persists - try to disable all extensions, relaunch VSCode and see if it works.
In case someone else have the same issue leave a post here or send me an email at solnurkarim@gmail.com

**Comment by solnurkarim** [comment]
Seems like an issue with activationEvents within package.json file. I'll try to implement some more ways to recognize file types to be provided with autocompletion to the next patch. Thanks for the participation.

**Comment by solnurkarim** [comment]
Resolved by adding activations to other stylesheet types.

**Comment by Jbandaru** [comment]
Still getting the same issue `command 'htmlToCssConfig' not found` when trying to run the command `HTML to CSS autocompletion: Extension Configuration`.

**Comment by solnurkarim** [comment]
> Still getting the same issue `command 'htmlToCssConfig' not found` when trying to run the command `HTML to CSS autocompletion: Extension Configuration`.

What CSS file extension are you using? Currently only .css, .scss, .sass, .styl and .less are being supported.
